import READY from './READY.js';
import MESSAGE_CREATE from './MESSAGE_CREATE.js';
import INTERACTION_CREATE from './INTERACTION_CREATE.js';

export const EVENTS = {
  READY,
  MESSAGE_CREATE,
  INTERACTION_CREATE
};